; Codice utile ad impaginare il PRETTYPRINT delle MDT

(load 'reverse.lisp)

(print '-)
(print '-)
(print '"TEST 1: ID in input '(() 1 (D E F))")
(print '-)
(mdtRev '(() 1 (D E F)) )
(print '-)

(print '-)
(print '-)
(print '"TEST 2: ID in input '(() 1 (D))")
(print '-)
(mdtRev '(() 1 (D)) )
(print '-)

(print '-)
(print '-)
(print '"TEST 3: ID in input '(() 1 (E))")
(print '-)
(mdtRev '(() 1 (E)) )
(print '-)

(print '-)
(print '-)
(print '"TEST 4: ID in input '(() 1 (F E))")
(print '-)
(mdtRev '(() 1 (F E)) )
(print '-)

(print '-)
(print '-)
(print '"TEST 5: ID in input '(() 1 (F E F E))")
(print '-)
(mdtRev '(() 1 (F E F E)) )
(print '-)

(print '-)
(print '-)
(print '"TEST 6: ID in input '(() 1 (D E E E E D))")
(print '-)
(mdtRev '(() 1 (D E E E E D)) )
(print '-)

(print '-)
(print '-)
(print '"TEST 7: ID in input '(() 1 (D E D D E))")
(print '-)
(mdtRev '(() 1 (D E D D E)) )
(print '-)

(print '-)
(print '-)
(print '"TEST 8: ID in input '(() 1 (F D E F F E D))")
(print '-)
(mdtRev '(() 1 (F D E F F E D)) )
(print '-)

(print '-)
(print '-)
(print '"TEST 9: ID in input '(() 1 (F D E D E E D))")
(print '-)
(mdtRev '(() 1 (F D E D E E D)) )
(print '-)

(print '-)
(print '-)
(print '"TEST 10: ID in input '(() 1 (D E F D E F))")
(print '-)
(mdtRev '(() 1 (D E F D E F)) )
(print '-)