; Codice utile ad impaginare il PRETTYPRINT delle MDT

(load 'somma.lisp)

(print '-)
(print '-)
(print '"TEST 1: ID in input '(() 1 (I B I))")
(print '-)
(mdtSum '(() 1 (I B I)) )
(print '-)

(print '-)
(print '-)
(print '"TEST 2: ID in input '(() 1 (I B I I))")
(print '-)
(mdtSum '(() 1 (I B I I)) )
(print '-)

(print '-)
(print '-)
(print '"TEST 3: ID in input '(() 1 (I I B I))")
(print '-)
(mdtSum '(() 1 (I I B I)) )
(print '-)

(print '-)
(print '-)
(print '"TEST 4: ID in input '(() 1 (I I I B I I))")
(print '-)
(mdtSum '(() 1 (I I I B I I)) )
(print '-)

(print '-)
(print '-)
(print '"TEST 5: ID in input '(() 1 (I I I B I I I I I))")
(print '-)
(mdtSum '(() 1 (I I I B I I I I I)) )
(print '-)

(print '-)
(print '-)
(print '"TEST 6: ID in input '(() 1 (I I I B I I I))")
(print '-)
(mdtSum '(() 1 (I I I B I I I)) )
(print '-)

(print '-)
(print '-)
(print '"TEST 7: ID in input '(() 1 (I I I I B I I I I))")
(print '-)
(mdtSum '(() 1 (I I I I B I I I I)) )
(print '-)

(print '-)
(print '-)
(print '"TEST 8: ID in input '(() 1 (I I I I I I B I))")
(print '-)
(mdtSum '(() 1 (I I I I I I B I)) )
(print '-)

(print '-)
(print '-)
(print '"TEST 9: ID in input '(() 1 (I I I I I B I I))")
(print '-)
(mdtSum '(() 1 (I I I I I B I I)) )
(print '-)

(print '-)
(print '-)
(print '"TEST 10: ID in input '(() 1 (I I B I I I I I I))")
(print '-)
(mdtSum '(() 1 (I I B I I I I I I)) )
(print '-)