; Codice utile ad impaginare il PRETTYPRINT delle MDT

(load 'sommabinaria.lisp)

(print '-)
(print '-)
(print '"TEST 1: ID in input '(() 1 (O B O))")
(print '-)
(mdtSub '(() 1 (O B O)) )
(print '-)

(print '-)
(print '-)
(print '"TEST 2: ID in input '(() 1 (O B I))")
(print '-)
(mdtSub '(() 1 (O B I)) )
(print '-)

(print '-)
(print '-)
(print '"TEST 3: ID in input '(() 1 (I B O))")
(print '-)
(mdtSub '(() 1 (I B O)) )
(print '-)

(print '-)
(print '-)
(print '"TEST 4: ID in input '(() 1 (I O B I))")
(print '-)
(mdtSub '(() 1 (I O B I)) )
(print '-)

(print '-)
(print '-)
(print '"TEST 5: ID in input '(() 1 (O O O O I O B I O O))")
(print '-)
(mdtSub '(() 1 (O O O O I O B I O O)) )
(print '-)

(print '-)
(print '-)
(print '"TEST 6: ID in input '(() 1 (I O I B I O I))")
(print '-)
(mdtSub '(() 1 (I O I B I O I)) )
(print '-)

(print '-)
(print '-)
(print '"TEST 7: ID in input '(() 1 (I B I O I O))")
(print '-)
(mdtSub '(() 1 (I B I O I O)) )
(print '-)

(print '-)
(print '-)
(print '"TEST 8: ID in input '(() 1 (I O O I I B I))")
(print '-)
(mdtSub '(() 1 (I O O I I B I)) )
(print '-)

(print '-)
(print '-)
(print '"TEST 9: ID in input '(() 1 (I O B O O I I))")
(print '-)
(mdtSub '(() 1 (I O B O O I I)) )
(print '-)

(print '-)
(print '-)
(print '"TEST 10: ID in input '(() 1 (I I B I I I I I I))")
(print '-)
(mdtSub '(() 1 (I I B I I I I I I)) )
(print '-)