; Definisco i dati per le elaborazioni
; Gli atomi sono le lettere dell'alfabeto; tranne t - atomo di sistema TRUE
; Le liste sono la lb lc ld le lf lg

(setq a 1)
(setq b 2)
(setq c 3)
(setq d 4)
(setq e 5)
(setq f 6)
(setq g 7)
(setq h 8)
(setq i 9)
(setq l 1)
(setq m 2)
(setq n 3)
(setq o 4)
(setq p 5)
(setq q 6)
(setq r 7)
(setq s 8)
(setq u 9)
(setq v 1)
(setq z 2)
(setq w 3)
(setq j 4)
(setq y 5)
(setq k 6)

(setq la '(a b c))
(setq lb '(d e f))
(setq lc '(g h i l m n))
(setq ld '(o p q r s u v z w j y k))
(setq le '(b e h p q))
(setq lf '(e f s u c b))
(setq lg '(a e i l s p u))